In [93]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import scale
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import f1_score

In [94]:
ds_ch = pd.read_csv('./Downloads/week4day1/통신고객이탈.csv',engine='python')
ds_ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 15 columns):
CHURN                 930 non-null object
CUSTOMER_ID           930 non-null object
GENDER                930 non-null object
AGE                   930 non-null int64
CHARGE_TYPE           930 non-null object
HANDSET               930 non-null object
USAGE_BAND            930 non-null object
SERVICE_DURATION      930 non-null float64
DROPPED_CALLS         930 non-null int64
PEAK_CALLS_NO         930 non-null int64
PEAK_CALLS_TIME       930 non-null float64
WEEKEND_CALLS_NO      930 non-null int64
WEEKEND_CALLS_TIME    930 non-null float64
TOTAL_CALLS_NO        930 non-null int64
TOTAL_CALLS_TIME      930 non-null float64
dtypes: float64(4), int64(5), object(6)
memory usage: 109.1+ KB

In [95]:
ds_sel=ds_ch.select_dtypes(exclude='object')
ds_sel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 9 columns):
AGE                   930 non-null int64
SERVICE_DURATION      930 non-null float64
DROPPED_CALLS         930 non-null int64
PEAK_CALLS_NO         930 non-null int64
PEAK_CALLS_TIME       930 non-null float64
WEEKEND_CALLS_NO      930 non-null int64
WEEKEND_CALLS_TIME    930 non-null float64
TOTAL_CALLS_NO        930 non-null int64
TOTAL_CALLS_TIME      930 non-null float64
dtypes: float64(4), int64(5)
memory usage: 65.5 KB

In [96]:
ds_ch_dummy=pd.get_dummies(ds_ch)
ds_ch_dummy.head()

,AGE,SERVICE_DURATION,DROPPED_CALLS,PEAK_CALLS_NO,PEAK_CALLS_TIME,WEEKEND_CALLS_NO,WEEKEND_CALLS_TIME,TOTAL_CALLS_NO,TOTAL_CALLS_TIME,CHURN_Active,...,HANDSET_S80,HANDSET_SOP10,HANDSET_SOP20,HANDSET_WC95,USAGE_BAND_High,USAGE_BAND_Low,USAGE_BAND_Med,USAGE_BAND_MedHigh,USAGE_BAND_MedLow,USAGE_BAND_None
0,31,33.33,6,218,379.8,9,21.6,366,632.4,1,...,0,0,0,0,0,0,1,0,0,0
1,27,30.87,10,373,656.4,11,28.0,411,810.4,1,...,0,0,0,0,0,0,1,0,0,0
2,27,49.40,11,260,582.0,0,0.0,265,614.1,1,...,0,0,0,0,0,0,1,0,0,0
3,61,48.60,1,294,661.8,14,101.5,326,844.0,1,...,0,0,0,0,0,0,1,0,0,0
4,52,56.03,0,221,555.6,7,25.0,274,673.0,1,...,0,0,0,0,0,0,1,0,0,0

In [97]:
ds_ch["CHURN"].replace(to_replace = "Active", value=0, inplace=True)
ds_ch["CHURN"].replace(to_replace = "Churned", value=1, inplace=True)
ds_sel["CHURN"]=ds_ch["CHURN"]
ds_ch_dummy=pd.get_dummies(ds_sel)
ds_ch_dummy.head()

/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,AGE,SERVICE_DURATION,DROPPED_CALLS,PEAK_CALLS_NO,PEAK_CALLS_TIME,WEEKEND_CALLS_NO,WEEKEND_CALLS_TIME,TOTAL_CALLS_NO,TOTAL_CALLS_TIME,CHURN
0,31,33.33,6,218,379.8,9,21.6,366,632.4,0
1,27,30.87,10,373,656.4,11,28.0,411,810.4,0
2,27,49.40,11,260,582.0,0,0.0,265,614.1,0
3,61,48.60,1,294,661.8,14,101.5,326,844.0,0
4,52,56.03,0,221,555.6,7,25.0,274,673.0,0

In [98]:
ds_ch_scaled = scale(ds_ch_dummy)
ds_ch_scaled = pd.DataFrame(ds_ch_scaled, columns = ds_ch_dummy.columns)
ds_ch_scaled["CHURN"] = ds_ch["CHURN"]
ds_ch_scaled.head()

/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.

,AGE,SERVICE_DURATION,DROPPED_CALLS,PEAK_CALLS_NO,PEAK_CALLS_TIME,WEEKEND_CALLS_NO,WEEKEND_CALLS_TIME,TOTAL_CALLS_NO,TOTAL_CALLS_TIME,CHURN
0,-0.030604,-0.069958,0.949112,-0.032834,-0.617357,-0.432263,-0.755024,0.079015,-0.783880,0
1,-0.335827,-0.243451,2.091732,0.651830,-0.080674,-0.307456,-0.579614,0.259163,-0.458260,0
2,-0.335827,1.063386,2.377387,0.152687,-0.225031,-0.993897,-1.347031,-0.325316,-0.817357,0
3,2.258568,1.006966,-0.479163,0.302872,-0.070196,-0.120245,1.434855,-0.081116,-0.396795,0
4,1.571816,1.530970,-0.764818,-0.019583,-0.276254,-0.557071,-0.661838,-0.289287,-0.709610,0

In [99]:
np.random.seed(seed=1234)
msk=np.random.rand(ds_ch_dummy.shape[0]) <0.7
ds_ch_train=ds_ch_dummy[msk]
ds_ch_test=ds_ch_dummy[~msk]

ds_ch_train_y=ds_ch_train["CHURN"]
ds_ch_train_x=ds_ch_train.drop("CHURN", axis=1, inplace=False)
ds_ch_test_y=ds_ch_test["CHURN"]
ds_ch_test_x=ds_ch_test.drop("CHURN", axis=1, inplace=False)

print("train data X size : {}".format(ds_ch_train_x.shape))
print("train data Y size : {}".format(ds_ch_train_y.shape))
print("test data X size : {}".format(ds_ch_test_x.shape))
print("test data Y size : {}".format(ds_ch_test_y.shape))

train data X size : (635, 9)
train data Y size : (635,)
test data X size : (295, 9)
test data Y size : (295,)

In [100]:
ds_ch_train_x_scaled=scale(ds_ch_train_x, axis=0)
ds_ch_test_x_scaled=scale(ds_ch_test_x, axis=0)
pd.DataFrame(ds_ch_train_x_scaled, columns=ds_ch_train_x.columns).head()

/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.
/home/pirl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.

,AGE,SERVICE_DURATION,DROPPED_CALLS,PEAK_CALLS_NO,PEAK_CALLS_TIME,WEEKEND_CALLS_NO,WEEKEND_CALLS_TIME,TOTAL_CALLS_NO,TOTAL_CALLS_TIME
0,-0.061287,-0.066658,0.936779,-0.050954,-0.622843,-0.431938,-0.777862,0.069711,-0.778293
1,-0.366521,-0.240702,2.073082,0.618542,-0.088273,-0.309382,-0.601091,0.247156,-0.454921
2,-0.366521,1.070294,2.357157,0.130457,-0.232062,-0.983441,-1.374462,-0.328554,-0.811538
3,1.464884,1.072417,0.084552,0.255718,-0.416436,-0.922163,-0.496134,0.310247,-0.286151
4,-0.137596,-0.139530,0.936779,0.851786,0.053197,-0.248104,0.083895,0.558670,-0.279066

In [101]:
model=["DecisionTree", "RandomForest", "GradientBoosting", "SVM"]
train_accuracy=[]
test_accuracy=[]
model_f1_score=[]

In [102]:
tree = DecisionTreeClassifier(criterion="gini", max_depth=10, min_samples_leaf=30,random_state=1234)
tree.fit(ds_ch_train_x_scaled, ds_ch_train_y)
train_accuracy.append(tree.score(ds_ch_train_x_scaled, ds_ch_train_y))
test_accuracy.append(tree.score(ds_ch_test_x_scaled, ds_ch_test_y))
model_f1_score.append(f1_score(ds_ch_test_y,tree.predict(ds_ch_test_x_scaled)))

In [103]:
rf = RandomForestClassifier(criterion="gini", n_estimators=100, max_depth=4, min_samples_leaf=30, random_state=1234)
rf.fit(ds_ch_train_x_scaled, ds_ch_train_y)
train_accuracy.append(rf.score(ds_ch_train_x_scaled, ds_ch_train_y))
test_accuracy.append(rf.score(ds_ch_test_x_scaled, ds_ch_test_y))
model_f1_score.append(f1_score(ds_ch_test_y,rf.predict(ds_ch_test_x_scaled)))

/home/pirl/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)

In [104]:
gb = GradientBoostingClassifier(learning_rate=0.1, max_depth=4, min_samples_leaf=30, n_estimators=5, random_state=1234)
gb.fit(ds_ch_train_x_scaled, ds_ch_train_y)
train_accuracy.append(gb.score(ds_ch_train_x_scaled, ds_ch_train_y))
test_accuracy.append(gb.score(ds_ch_test_x_scaled, ds_ch_test_y))
model_f1_score.append(f1_score(ds_ch_test_y,gb.predict(ds_ch_test_x_scaled)))

/home/pirl/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)

In [105]:
svm = SVC(C=6, gamma=0.1, random_state=1234)
svm.fit(ds_ch_train_x_scaled, ds_ch_train_y)
train_accuracy.append(svm.score(ds_ch_train_x_scaled, ds_ch_train_y))
test_accuracy.append(svm.score(ds_ch_test_x_scaled, ds_ch_test_y))
model_f1_score.append(f1_score(ds_ch_test_y,svm.predict(ds_ch_test_x_scaled)))

In [106]:
ds_eval=pd.DataFrame(index=model)
ds_eval["TrainAccuracy"]=train_accuracy
ds_eval["TestAccuracy"]=test_accuracy
ds_eval["F1Score"]=model_f1_score
ds_eval.round(3)

                  TrainAccuracy  TestAccuracy  F1Score
DecisionTree              0.833         0.766    0.289
RandomForest              0.808         0.803    0.000
GradientBoosting          0.808         0.803    0.000
SVM                       0.871         0.797    0.250